version: '3.7'

services:

  es01:
    container_name: es01
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    env_file:
      - es.env
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: data01
        target: /usr/share/elasticsearch/data

    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  es02:
    container_name: es02
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    env_file:
      - .env
      - es.env
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: data02
        target: /usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elk

  es03:
    container_name: es03
    build:
      context: elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    env_file:
      - .env
      - es.env
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: data03
        target: /usr/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - elk

  kib:
    container_name: kib
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - 5601:5601
    depends_on:
      - es01
      - es02
      - es03
      - logstash
    networks:
      - elk

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/config/pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml
        read_only: true
    ports:
      - 5044:5044  # beat
      - 5000-5012  # logback, fluent, other ...
      - 9600-9700  # default ports
    depends_on:
      - es01
      - es02
      - es03
    networks:
      - elk

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elk:
    driver: bridge
