version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    container_name: my_postgres
    environment:
      POSTGRES_USER: ps
      POSTGRES_PASSWORD: secret
    ports:
    - 5432:5432