version: '3.7'

# docker-compose -f docker-compose-kafka-single.yml up -d
# docker-compose -f docker-compose-kafka-single.yml scale ps_kafka_scale=3
services:

  ps_kafka_scale:
    image: wurstmeister/kafka
    ports:
    - 9092:9092
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2" # Normal instances
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - ps-zoo

networks:
  ps-zoo:
    external: true