version: '3.7'

services:

  my_kafka_1:
    image: wurstmeister/kafka
    container_name: my_kafka_1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_LOG_ROLL_MS: 10000
      KAFKA_LOG_CLEANUP_PLOICY: compact
#      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
    networks:
      - ps-zoo

networks:
  ps-zoo:
    external: true