version: '3.6'

networks:
  ps_kafka_network:

services:
  ps_zookeeper:
    image:  wurstmeister/zookeeper:3.4.6
    container_name: ps_zookeeper
    ports:
      - "2181:2181"
    networks:
      - ps_kafka_network

  ps_kafka:
    image: wurstmeister/kafka:2.12-2.0.1
    container_name: ps_kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: ps_zookeeper:2181
      KAFKA_CREATE_TOPICS: 'psawesome-topic:1:1' # Topic명 : partition개수 : replica 개수
      KAFKA_HEAP_OPTS: "-Xms512m -Xmx2g"
    ports:
      - "9092:9092"
    depends_on:
      - ps_zookeeper
    networks:
      - ps_kafka_network
