version: '3.7'

services:

  ps_kafka_one:
    image: wurstmeister/kafka
    container_name: ps_kafka_one
    hostname: ps_kafka_one
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ps_kafka_one
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://ps_kafka_one:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LOG_ROLL_MS: 10000
      KAFKA_CREATE_TOPICS: "test-java:1:1,test-python:1:1"
    #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    #      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
#    extra_hosts:
#      - "ps_kafka_one:127.0.0.1"
#      - 'ps_kafka_two:127.0.0.1'
#      - 'ps_kafka_three:127.0.0.1'
    networks:
      - ps-zoo

  ps_kafka_two:
    image: wurstmeister/kafka
    container_name: ps_kafka_two
    hostname: ps_kafka_two
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: ps_kafka_two
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://ps_kafka_two:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LOG_ROLL_MS: 10000
      KAFKA_CREATE_TOPICS: "test-java:1:1,test-python:1:1"
    #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    #      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
#    extra_hosts:
#      - "ps_kafka_one:127.0.0.1"
#      - 'ps_kafka_two:127.0.0.1'
#      - 'ps_kafka_three:127.0.0.1'
    networks:
      - ps-zoo

  ps_kafka_three:
    image: wurstmeister/kafka
    container_name: ps_kafka_three
    hostname: ps_kafka_three
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: ps_kafka_three
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://ps_kafka_three:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LOG_ROLL_MS: 10000
      KAFKA_CREATE_TOPICS: "test-java:1:1,test-python:1:1"
    #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    #      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
#    extra_hosts:
#      - "ps_kafka_one:127.0.0.1"
#      - 'ps_kafka_two:127.0.0.1'
#      - 'ps_kafka_three:127.0.0.1'
    networks:
      - ps-zoo


networks:
  ps-zoo:
    external: true
