version: '3.7'

services:

  ps_kafka_one:
    image: wurstmeister/kafka
    container_name: ps_kafka_one
    hostname: 54.180.91.69
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 54.180.91.69
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2" # Normal instances
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_ROLL_MS: 10000
      KAFKA_LOG_CLEANUP_PLOICY: compact
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    #      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
    networks:
      - ps-zoo

  ps_kafka_two:
    image: wurstmeister/kafka
    container_name: ps_kafka_two
    hostname: 54.180.91.69
    ports:
      - 9093:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 54.180.91.69
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2" # Normal instances
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_ROLL_MS: 10000
      KAFKA_LOG_CLEANUP_PLOICY: compact
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    #      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
    networks:
      - ps-zoo

  ps_kafka_three:
    image: wurstmeister/kafka
    container_name: ps_kafka_three
    hostname: 54.180.91.69
    ports:
      - 9094:9092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 54.180.91.69
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2" # Normal instances
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_ROLL_MS: 10000
      KAFKA_LOG_CLEANUP_PLOICY: compact
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    #      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
    networks:
      - ps-zoo


networks:
  ps-zoo:
    external: true