version: '3.7'

services:

  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ps-zoo


networks:
  ps-zoo:
    external: true
